[package]
name = "raikiri"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.7", features = ["derive"] }
clap_derive = { version = "4.5.5" }
futures = "0.3.30"
homedir = "0.2.1"
regex = "1.10.5"
tokio = { version = "1.38.0", features = ["full"] }
wasmtime = "22.0.0"
wasmtime-wasi = "22.0.0"
whoami = "1.5.1"
wit-bindgen = "0.27.0"
