[package]
name = "verify-component-adapter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
wasmparser = { workspace = true, features = ['std', 'validate'] }
wat = { workspace = true }
anyhow = { workspace = true, features = ['std'] }
