[package]
name = "test-programs"
version = "0.0.0"
edition = "2021"

[dependencies]
wit-bindgen = "0.41.0"
waki = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
raikiri-wasi-sdk = { workspace = true }